
drop table countries; 

create table countries(country text, continent text);

CREATE INDEX continent_idx ON countries (continent);


insert into countries (continent, country) values ('Africa',	replace('Algeria                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Angola                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Benin                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Botswana                               ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Burkina                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Burundi                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Cameroon                               ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Cape Verde                             ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Central African Republic               ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Chad                                   ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Comoros                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Congo                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Congo, Democratic Republic of          ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Djibouti                               ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Egypt                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Equatorial Guinea                      ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Eritrea                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Ethiopia                               ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Gabon                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Gambia                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Ghana                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Guinea                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Guinea-Bissau                          ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Ivory Coast                            ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Kenya                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Lesotho                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Liberia                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Libya                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Madagascar                             ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Malawi                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Mali                                   ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Mauritania                             ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Mauritius                              ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Morocco                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Mozambique                             ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Namibia                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Niger                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Nigeria                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Rwanda                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Sao Tome and Principe                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Senegal                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Seychelles                             ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Sierra Leone                           ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Somalia                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('South Africa                           ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('South Sudan                            ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Sudan                                  ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Swaziland                              ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Tanzania                               ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Togo                                   ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Tunisia                                ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Uganda                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Zambia                                 ',' ','') );
insert into countries (continent, country) values ('Africa',	replace('Zimbabwe                               ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Afghanistan                                ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Bahrain                                    ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Bangladesh                                 ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Bhutan                                     ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Brunei                                     ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Burma (Myanmar)                            ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Cambodia                                   ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('China                                      ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('East Timor                                 ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('India                                      ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Indonesia                                  ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Iran                                       ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Iraq                                       ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Israel                                     ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Japan                                      ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Jordan                                     ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Kazakhstan                                 ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Korea, North                               ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Korea, South                               ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Kuwait                                     ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Kyrgyzstan                                 ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Laos                                       ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Lebanon                                    ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Malaysia                                   ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Maldives                                   ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Mongolia                                   ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Nepal                                      ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Oman                                       ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Pakistan                                   ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Philippines                                ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Qatar                                      ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Russian Federation                         ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Saudi Arabia                               ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Singapore                                  ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Sri Lanka                                  ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Syria                                      ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Tajikistan                                 ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Thailand                                   ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Turkey                                     ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Turkmenistan                               ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('United Arab Emirates                       ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Uzbekistan                                 ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Vietnam                                    ',' ','') );
insert into countries (continent, country) values ('Asia',	replace('Yemen                                      ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Albania                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Andorra                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Armenia                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Austria                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Azerbaijan                             ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Belarus                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Belgium                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Bosnia and Herzegovina                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Bulgaria                               ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Croatia                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Cyprus                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('CZ                                     ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Denmark                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Estonia                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Finland                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('France                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Georgia                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Germany                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Greece                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Hungary                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Iceland                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Ireland                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Italy                                  ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Latvia                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Liechtenstein                          ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Lithuania                              ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Luxembourg                             ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Macedonia                              ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Malta                                  ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Moldova                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Monaco                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Montenegro                             ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Netherlands                            ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Norway                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Poland                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Portugal                               ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Romania                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('San Marino                             ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Serbia                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Slovakia                               ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Slovenia                               ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Spain                                  ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Sweden                                 ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Switzerland                            ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Ukraine                                ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('United Kingdom                         ',' ','') );
insert into countries (continent, country) values ('Europe',	replace('Vatican City                           ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Antigua and Barbuda                ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Bahamas                            ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Barbados                           ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Belize                             ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Canada                             ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Costa Rica                         ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Cuba                               ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Dominica                           ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Dominican Republic                 ',' ','') );
insert into countries (continent, country) values ('North America',	replace('El Salvador                        ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Grenada                            ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Guatemala                          ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Haiti                              ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Honduras                           ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Jamaica                            ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Mexico                             ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Nicaragua                          ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Panama                             ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Saint Kitts and Nevis              ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Saint Lucia                        ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Saint Vincent and the Grenadine    ',' ','') );
insert into countries (continent, country) values ('North America',	replace('Trinidad and Tobago                ',' ','') );
insert into countries (continent, country) values ('North America',	replace('US                                 ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Australia                              ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Fiji                                   ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Kiribati                               ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Marshall Islands                       ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Micronesia                             ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Nauru                                  ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('New Zealand                            ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Palau                                  ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Papua New Guinea                       ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Samoa                                  ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Solomon Islands                        ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Tonga                                  ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Tuvalu                                 ',' ','') );
insert into countries (continent, country) values ('Oceania',	replace('Vanuatu                                ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Argentina                          ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Bolivia                            ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Brazil                             ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Chile                              ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Colombia                           ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Ecuador                            ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Guyana                             ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Paraguay                           ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Peru                               ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Suriname                           ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Uruguay                            ',' ','') );
insert into countries (continent, country) values ('South America',	replace('Venezuela                          ',' ','') );



